export const DEMO_CUSTOMERS = [
  {
    id: 'customer_001',
    name: 'Acme Corp',
    tier: 'Enterprise SLA',
    initials: 'AC',
    badgeClass: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    avatarGradient: 'from-blue-600 to-indigo-600',
    desc: 'B2B Analytics & Cloud Operations',
  },
  {
    id: 'customer_hackathon_demo',
    name: 'Acme Hackathon Demo',
    tier: 'Live Demo Account',
    initials: 'HD',
    badgeClass: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    avatarGradient: 'from-cyan-600 to-blue-600',
    desc: 'Clean 60-Second Demo Account',
  },
  {
    id: 'customer_002',
    name: 'TechNova',
    tier: 'Growth Tier',
    initials: 'TN',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-violet-600',
    desc: 'Isolated Customer (Zero Data Leakage)',
  },
  {
    id: 'customer_ticket_demo_001',
    name: 'Acme Ticket Demo',
    tier: 'Enterprise Demo',
    initials: 'TD',
    badgeClass: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    avatarGradient: 'from-amber-600 to-orange-600',
    desc: 'Ticket & Escalation Demo',
  },
  {
    id: 'customer_preference_demo_001',
    name: 'Acme Preference Demo',
    tier: 'Enterprise Demo',
    initials: 'PD',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-indigo-600',
    desc: 'Preference Learning Demo',
  },
  {
    id: 'customer_003',
    name: 'Nova Systems',
    tier: 'Business Tier',
    initials: 'NS',
    badgeClass: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    avatarGradient: 'from-emerald-600 to-teal-600',
    desc: 'Logistics Infrastructure',
  },
];
