export const DEMO_CUSTOMERS = [
  {
    id: 'customer_preference_demo_001',
    name: 'Acme Preference Demo',
    tier: 'Enterprise Demo',
    initials: 'PD',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-indigo-600',
    desc: 'Preference Learning Demo',
  },
  {
    id: 'customer_preference_demo_002',
    name: 'TechNova Preference Demo',
    tier: 'Growth Demo',
    initials: 'TD',
    badgeClass: 'bg-slate-500/10 text-slate-400 border-slate-500/30',
    avatarGradient: 'from-slate-600 to-slate-700',
    desc: 'Isolated Preference Demo',
  },
  {
    id: 'customer_clean_demo_001',
    name: 'Acme Clean Demo',
    tier: 'Enterprise Demo',
    initials: 'CD',
    badgeClass: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    avatarGradient: 'from-cyan-600 to-blue-600',
    desc: 'Clean Phase 3 Demo Account',
  },
  {
    id: 'customer_clean_demo_002',
    name: 'TechNova Clean Demo',
    tier: 'Growth Demo',
    initials: 'TD',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-violet-600',
    desc: 'Isolated Demo Account',
  },
  {
    id: 'customer_demo_001',
    name: 'Acme Demo Corp',
    tier: 'Enterprise Demo',
    initials: 'AD',
    badgeClass: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    avatarGradient: 'from-cyan-600 to-blue-600',
    desc: 'Demo Account',
  },
  {
    id: 'customer_demo_002',
    name: 'TechNova Demo',
    tier: 'Growth Demo',
    initials: 'TD',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-violet-600',
    desc: 'Isolated Demo Account',
  },
  {
    id: 'customer_001',
    name: 'Acme Corp',
    tier: 'Enterprise SLA',
    initials: 'AC',
    badgeClass: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    avatarGradient: 'from-blue-600 to-indigo-600',
    desc: 'B2B Operations Platform',
  },
  {
    id: 'customer_002',
    name: 'TechNova',
    tier: 'Growth Tier',
    initials: 'TN',
    badgeClass: 'bg-purple-500/10 text-purple-400 border-purple-500/30',
    avatarGradient: 'from-purple-600 to-violet-600',
    desc: 'Supply Chain Operations',
  },
  {
    id: 'customer_003',
    name: 'Nova Systems',
    tier: 'Business Tier',
    initials: 'NS',
    badgeClass: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    avatarGradient: 'from-emerald-600 to-teal-600',
    desc: 'Logistics Infrastructure',
  },
];
