/**
 * Placement Role Catalog & Skill Requirements
 * Structured static configuration for engineering and analytics placement profiles.
 */

export const ROLE_CATALOG = {
  'Software Engineer': {
    title: 'Software Engineer',
    category: 'Engineering',
    description: 'Generalist software engineering role focusing on algorithmic problem solving, clean system design, and software fundamentals.',
    skills: [
      { name: 'Data Structures & Algorithms', importance: 'high', category: 'core', minProficiency: 'advanced' },
      { name: 'Object-Oriented Programming', importance: 'high', category: 'core', minProficiency: 'intermediate' },
      { name: 'System Design', importance: 'medium', category: 'system', minProficiency: 'intermediate' },
      { name: 'Database Management Systems', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Operating Systems & Concurrency', importance: 'medium', category: 'system', minProficiency: 'intermediate' },
      { name: 'Computer Networks', importance: 'medium', category: 'core', minProficiency: 'intermediate' },
      { name: 'Git & Version Control', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
    ],
  },

  'Backend Developer': {
    title: 'Backend Developer',
    category: 'Engineering',
    description: 'Server-side engineering role focused on high-throughput APIs, distributed systems, relational & NoSQL databases, and cloud infrastructure.',
    skills: [
      { name: 'Node.js / Express', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'SQL', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'RESTful API Design', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Structures & Algorithms', importance: 'high', category: 'core', minProficiency: 'intermediate' },
      { name: 'MongoDB / NoSQL', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'System Design & Scalability', importance: 'high', category: 'system', minProficiency: 'intermediate' },
      { name: 'Docker & Containerization', importance: 'medium', category: 'system', minProficiency: 'beginner' },
      { name: 'Caching & Redis', importance: 'medium', category: 'system', minProficiency: 'beginner' },
    ],
  },

  'Frontend Developer': {
    title: 'Frontend Developer',
    category: 'Engineering',
    description: 'Client-side web development focused on modern interactive UIs, reactive state management, CSS architecture, and web performance.',
    skills: [
      { name: 'JavaScript', importance: 'high', category: 'core', minProficiency: 'advanced' },
      { name: 'React', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'HTML & CSS', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'TypeScript', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Responsive Web Design', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'State Management', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Web Performance Optimization', importance: 'medium', category: 'system', minProficiency: 'beginner' },
      { name: 'Git & Version Control', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
    ],
  },

  'Full Stack Developer': {
    title: 'Full Stack Developer',
    category: 'Engineering',
    description: 'End-to-end web engineering covering responsive frontend interfaces, REST/GraphQL APIs, backend services, and database integration.',
    skills: [
      { name: 'JavaScript', importance: 'high', category: 'core', minProficiency: 'advanced' },
      { name: 'React', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Node.js / Express', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'SQL', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'RESTful API Design', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'MongoDB / NoSQL', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'HTML & CSS', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Structures & Algorithms', importance: 'medium', category: 'core', minProficiency: 'intermediate' },
      { name: 'Git & Version Control', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
    ],
  },

  'Data Analyst': {
    title: 'Data Analyst',
    category: 'Analytics',
    description: 'Business-driven data analytics role analyzing raw data, writing complex SQL transformations, computing statistical metrics, and authoring executive dashboards.',
    skills: [
      { name: 'SQL', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'Excel & Spreadsheets', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Statistics & Probability', importance: 'high', category: 'core', minProficiency: 'intermediate' },
      { name: 'Python', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Power BI', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Visualization', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Business Analysis', importance: 'medium', category: 'domain', minProficiency: 'intermediate' },
    ],
  },

  'Data Scientist': {
    title: 'Data Scientist',
    category: 'AI & Data Science',
    description: 'Analytical modeling role developing predictive algorithms, statistical hypotheses, feature pipelines, and machine learning models.',
    skills: [
      { name: 'Python', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'SQL', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Machine Learning', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Statistics & Probability', importance: 'high', category: 'core', minProficiency: 'advanced' },
      { name: 'Pandas & NumPy', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Visualization', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Feature Engineering', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Deep Learning', importance: 'low', category: 'technical', minProficiency: 'beginner' },
    ],
  },

  'Machine Learning Engineer': {
    title: 'Machine Learning Engineer',
    category: 'AI & Data Science',
    description: 'Production ML engineering bridging data science and software engineering to deploy scalable ML pipelines, model serving, and feature stores.',
    skills: [
      { name: 'Python', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'Machine Learning', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'Data Structures & Algorithms', importance: 'high', category: 'core', minProficiency: 'intermediate' },
      { name: 'Deep Learning', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'MLOps & Model Deployment', importance: 'high', category: 'system', minProficiency: 'intermediate' },
      { name: 'Docker & Containerization', importance: 'medium', category: 'system', minProficiency: 'intermediate' },
      { name: 'SQL', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'PyTorch / TensorFlow', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
    ],
  },

  'AI Engineer': {
    title: 'AI Engineer',
    category: 'AI & Data Science',
    description: 'Modern AI role building LLM-powered applications, prompt pipelines, agentic workflows, embeddings, and cognitive API integrations.',
    skills: [
      { name: 'Python', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'Prompt Engineering', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'LLM Frameworks (LangChain / LlamaIndex)', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'RESTful API Design', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Structures & Algorithms', importance: 'medium', category: 'core', minProficiency: 'intermediate' },
      { name: 'Vector Search & Embeddings', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
      { name: 'System Design', importance: 'medium', category: 'system', minProficiency: 'intermediate' },
      { name: 'Git & Version Control', importance: 'medium', category: 'technical', minProficiency: 'intermediate' },
    ],
  },

  'Data Engineer': {
    title: 'Data Engineer',
    category: 'Engineering',
    description: 'Infrastructure and pipeline role designing scalable ETL/ELT pipelines, distributed data stores, stream processing, and warehouse architectures.',
    skills: [
      { name: 'SQL', importance: 'high', category: 'technical', minProficiency: 'advanced' },
      { name: 'Python', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Data Warehousing & Modeling', importance: 'high', category: 'system', minProficiency: 'intermediate' },
      { name: 'ETL / ELT Pipelines', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Distributed Systems & Spark', importance: 'high', category: 'system', minProficiency: 'intermediate' },
      { name: 'Database Management Systems', importance: 'high', category: 'technical', minProficiency: 'intermediate' },
      { name: 'Docker & Containerization', importance: 'medium', category: 'system', minProficiency: 'intermediate' },
      { name: 'Cloud Fundamentals (AWS/GCP/Azure)', importance: 'medium', category: 'system', minProficiency: 'beginner' },
    ],
  },
};

/**
 * Role Alias Mapping for flexible matching of user target role queries
 */
export const ROLE_ALIASES = {
  'swe': 'Software Engineer',
  'sde': 'Software Engineer',
  'sde-1': 'Software Engineer',
  'sde 1': 'Software Engineer',
  'software engineer': 'Software Engineer',
  'software developer': 'Software Engineer',
  'software engineering': 'Software Engineer',

  'backend': 'Backend Developer',
  'backend developer': 'Backend Developer',
  'backend engineer': 'Backend Developer',
  'backend sde': 'Backend Developer',
  'node developer': 'Backend Developer',

  'frontend': 'Frontend Developer',
  'frontend developer': 'Frontend Developer',
  'frontend engineer': 'Frontend Developer',
  'ui developer': 'Frontend Developer',
  'react developer': 'Frontend Developer',

  'fullstack': 'Full Stack Developer',
  'full stack': 'Full Stack Developer',
  'full stack developer': 'Full Stack Developer',
  'full stack engineer': 'Full Stack Developer',

  'da': 'Data Analyst',
  'data analyst': 'Data Analyst',
  'data analytics': 'Data Analyst',
  'business intelligence': 'Data Analyst',
  'bi analyst': 'Data Analyst',

  'ds': 'Data Scientist',
  'data scientist': 'Data Scientist',
  'data science': 'Data Scientist',

  'mle': 'Machine Learning Engineer',
  'ml engineer': 'Machine Learning Engineer',
  'machine learning': 'Machine Learning Engineer',
  'machine learning engineer': 'Machine Learning Engineer',

  'ai engineer': 'AI Engineer',
  'ai developer': 'AI Engineer',
  'artificial intelligence engineer': 'AI Engineer',

  'de': 'Data Engineer',
  'data engineer': 'Data Engineer',
  'data engineering': 'Data Engineer',
};

/**
 * Skill Alias Mapping for deterministic normalization
 */
export const SKILL_ALIASES = {
  // Core languages
  'javascript': 'javascript',
  'js': 'javascript',
  'ecmascript': 'javascript',
  'typescript': 'typescript',
  'ts': 'typescript',
  'python': 'python',
  'py': 'python',
  'python3': 'python',
  'java': 'java',
  'c++': 'c++',
  'cpp': 'c++',
  'c': 'c',

  // Web & Frameworks
  'react': 'react',
  'reactjs': 'react',
  'react.js': 'react',
  'node': 'node.js / express',
  'nodejs': 'node.js / express',
  'node.js': 'node.js / express',
  'express': 'node.js / express',
  'expressjs': 'node.js / express',
  'node.js / express': 'node.js / express',
  'html': 'html & css',
  'css': 'html & css',
  'html5': 'html & css',
  'css3': 'html & css',
  'html & css': 'html & css',
  'responsive web design': 'responsive web design',
  'responsive design': 'responsive web design',
  'state management': 'state management',
  'redux': 'state management',

  // Database & SQL
  'sql': 'sql',
  'mysql': 'sql',
  'postgresql': 'sql',
  'postgres': 'sql',
  'database': 'database management systems',
  'dbms': 'database management systems',
  'database management systems': 'database management systems',
  'mongodb': 'mongodb / nosql',
  'nosql': 'mongodb / nosql',
  'mongodb / nosql': 'mongodb / nosql',
  'caching': 'caching & redis',
  'redis': 'caching & redis',
  'caching & redis': 'caching & redis',

  // Core CS
  'dsa': 'data structures & algorithms',
  'data structures': 'data structures & algorithms',
  'algorithms': 'data structures & algorithms',
  'data structures & algorithms': 'data structures & algorithms',
  'data structures and algorithms': 'data structures & algorithms',
  'oop': 'object-oriented programming',
  'oops': 'object-oriented programming',
  'object-oriented programming': 'object-oriented programming',
  'system design': 'system design & scalability',
  'system design & scalability': 'system design & scalability',
  'operating systems': 'operating systems & concurrency',
  'os': 'operating systems & concurrency',
  'operating systems & concurrency': 'operating systems & concurrency',
  'computer networks': 'computer networks',
  'cn': 'computer networks',
  'networking': 'computer networks',
  'git': 'git & version control',
  'github': 'git & version control',
  'version control': 'git & version control',
  'git & version control': 'git & version control',

  // Data & Analytics
  'excel': 'excel & spreadsheets',
  'spreadsheets': 'excel & spreadsheets',
  'excel & spreadsheets': 'excel & spreadsheets',
  'statistics': 'statistics & probability',
  'probability': 'statistics & probability',
  'stats': 'statistics & probability',
  'statistics & probability': 'statistics & probability',
  'power bi': 'power bi',
  'powerbi': 'power bi',
  'tableau': 'data visualization',
  'data visualization': 'data visualization',
  'visualization': 'data visualization',
  'business analysis': 'business analysis',
  'business analytics': 'business analysis',
  'pandas': 'pandas & numpy',
  'numpy': 'pandas & numpy',
  'pandas & numpy': 'pandas & numpy',
  'feature engineering': 'feature engineering',

  // AI & ML
  'machine learning': 'machine learning',
  'ml': 'machine learning',
  'deep learning': 'deep learning',
  'dl': 'deep learning',
  'mlops': 'mlops & model deployment',
  'mlops & model deployment': 'mlops & model deployment',
  'model deployment': 'mlops & model deployment',
  'pytorch': 'pytorch / tensorflow',
  'tensorflow': 'pytorch / tensorflow',
  'keras': 'pytorch / tensorflow',
  'pytorch / tensorflow': 'pytorch / tensorflow',
  'prompt engineering': 'prompt engineering',
  'llm': 'llm frameworks (langchain / llamaindex)',
  'llms': 'llm frameworks (langchain / llamaindex)',
  'langchain': 'llm frameworks (langchain / llamaindex)',
  'llamaindex': 'llm frameworks (langchain / llamaindex)',
  'llm frameworks (langchain / llamaindex)': 'llm frameworks (langchain / llamaindex)',
  'vector search': 'vector search & embeddings',
  'embeddings': 'vector search & embeddings',
  'vector search & embeddings': 'vector search & embeddings',

  // Infrastructure & Cloud
  'docker': 'docker & containerization',
  'containers': 'docker & containerization',
  'containerization': 'docker & containerization',
  'docker & containerization': 'docker & containerization',
  'rest': 'restful api design',
  'rest api': 'restful api design',
  'api': 'restful api design',
  'restful api design': 'restful api design',
  'data warehousing': 'data warehousing & modeling',
  'data warehousing & modeling': 'data warehousing & modeling',
  'etl': 'etl / elt pipelines',
  'elt': 'etl / elt pipelines',
  'etl / elt pipelines': 'etl / elt pipelines',
  'spark': 'distributed systems & spark',
  'pyspark': 'distributed systems & spark',
  'distributed systems': 'distributed systems & spark',
  'distributed systems & spark': 'distributed systems & spark',
  'cloud': 'cloud fundamentals (aws/gcp/azure)',
  'aws': 'cloud fundamentals (aws/gcp/azure)',
  'gcp': 'cloud fundamentals (aws/gcp/azure)',
  'azure': 'cloud fundamentals (aws/gcp/azure)',
  'cloud fundamentals (aws/gcp/azure)': 'cloud fundamentals (aws/gcp/azure)',
  'web performance': 'web performance optimization',
  'web performance optimization': 'web performance optimization',
};
